version: "3"

networks:
    proxy:
      driver: bridge

services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: 'true'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../Proxy/conf/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - ../Proxy/logs/global:/var/log/nginx
      - ../Proxy/vhost:/etc/nginx/vhost.d
      - ../Proxy/passwd:/etc/nginx/htpasswd
      - ../Proxy/data/html:/usr/share/nginx/html
      - ../Proxy/data/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - ../Proxy/vhost:/etc/nginx/vhost.d
      - ../Proxy/data/html:/usr/share/nginx/html
      - ../Proxy/data/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx
    networks:
      - proxy

  wordpress-db:
    container_name: wordpress-db
    image: mariadb:latest
    restart: always
    volumes:
      - ./wordpress/db_data:/var/lib/mysql
    networks:
      - wp-net
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: $V_DB_NAME
      MYSQL_USER: $V_DB_USER
      MYSQL_PASSWORD: $V_DB_PASSWORD
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -s --database=$$MYSQL_DATABASE -e 'SHOW TABLES;'"
      interval: 30s
      timeout: 3s
      retries: 2

  wordpress-web:
    container_name: wordpress-web
    image: wordpress:latest
    depends_on:
      - wordpress-db
    restart: always
    volumes:
      - ./wordpress/html:/var/www/html:rw
      - ./wordpress/.htaccess:/var/www/html/.htaccess:ro
    networks:
      - proxy
      - wp-net
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_NAME: $V_DB_NAME
      WORDPRESS_DB_USER: $V_DB_USER
      WORDPRESS_DB_PASSWORD: $V_DB_PASSWORD
      WORDPRESS_TABLE_PREFIX: $V_WP_TABLE_PREFIX
      VIRTUAL_HOST: $V_VIRTUAL_HOST
      VIRTUAL_PORT: $V_VIRTUAL_PORT
      LETSENCRYPT_HOST: $V_VIRTUAL_HOST
      LETSENCRYPT_EMAIL: $V_LETSENCRYPT_EMAIL
    healthcheck:
      test: "curl -Ls -o /dev/null -w \"%{http_code}\n%{url_effective}\n\" http://localhost:$$VIRTUAL_PORT"
      interval: 30s
      timeout: 3s
      retries: 2
